INSERT INTO items VALUES 
(    'iPhone 11', 
    'A2221', 
    194, 
    '01-09-2019', 
    999,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Apple'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Smartphone')), 

(    'MacBook Pro', 
    'MV902', 
    1830, 
    '01-05-2019', 
    2499,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Apple'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Laptop')),

(
   'Lenovo Ideapad 330', 
    '81F500ATSP', 
    2200, 
    '01-12-2019', 
    599,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Lenovo'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Laptop')),

(   'Acer Swift 5', 
    'SF514-54T', 
    970, 
    '01-09-2019', 
    1249,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Acer'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Laptop')), 

(    'Nikon Coolpix L32',
    '25495', 
    148, 
    '01-12-2015', 
    79,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Nixon'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Camera')),

(    'Huawei P20 Lite Semi-Transparent', 
    'ANE-LX2', 
    145, 
    '01-02-2019', 
    269,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Huawei'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Smartphone')), 

(    'Iiyama ProLite XUB2792QSU-B1',
    'BLH-L-P2792QSU', 
    4600, 
    '01-01-2019', 
    299,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Iiyama'),
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Monitor')),

(    'Logitech G502', 
    '910008339', 
    121, 
    '01-01-2019', 
    49,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Logitech'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Mouse')), 

(    'Canon EOS M50', 
    'EOSM50KIS', 
    3900, 
    '01-02-2018', 
    599,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Canon'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Camera')),

(    'Sony WH-1000XM3', 
    'WH1000XM3/B', 
    255, 
    '01-08-2018', 
    349,
    (SELECT Makers.Id FROM Makers WHERE Makers.Name = 'Sony'), 
    (SELECT Types.Id FROM Types WHERE Types.Name = 'Headphones'));