//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Model.DBF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBFConnection : DbContext
    {
        public DBFConnection()
            : base("name=DBFConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Fails> Fails { get; set; }
        public virtual DbSet<ItemCountry> ItemCountry { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Makers> Makers { get; set; }
        public virtual DbSet<Quantities> Quantities { get; set; }
        public virtual DbSet<Sellings> Sellings { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Types> Types { get; set; }
    }
}
