//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Model.DBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.ItemCountry = new HashSet<ItemCountry>();
            this.Sellings = new HashSet<Sellings>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public Nullable<int> Maker { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<System.DateTime> Release { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemCountry> ItemCountry { get; set; }
        public virtual Makers Makers { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sellings> Sellings { get; set; }
    }
}
