//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject.Model.DBF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCountry
    {
        public int ItemId { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> QuantityId { get; set; }
        public Nullable<int> FailsId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Fails Fails { get; set; }
        public virtual Items Items { get; set; }
        public virtual Quantities Quantities { get; set; }
    }
}
